#!/usr/bin/env bash
# file: active-window-cwd

if [ $(active-shell-pid) == -1 ]; then
    exec echo "$(cwd)"
fi

exec echo "$(ls -al /proc/$(active-shell-pid)/cwd | awk '{$1=$2=$3=$4=$5=$6=$7=$8=$9=$10=""; print $0}' | xargs)"

