#!/usr/bin/env bash
# file: i3blurlock

# Dependencies: scrot, imagemagick, i3lock

PLAIN=/tmp/i3blurlock_plain.png
BLURRED=/tmp/i3blurlock_blurred.png

SHRINK=20%
ENLARGE=500%

scrot $PLAIN
#convert $PLAIN -blur 0x5 $BLURRED
convert $PLAIN -level 0%,100%,0.6 -filter Gaussian -resize $SHRINK -define filter:sigma=1.5 -resize $ENLARGE /home/lookaasheq/Dropbox/projects/arch-config/home/username/scripts/lock.png -gravity center -composite  $BLURRED 
i3lock -i $BLURRED

